@startuml
title ИС Умный Дом - Payment Service Component Diagram

top to bottom direction

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml
Container(ApiGateway, "API Gateway", "Java, Spring")
Container(CoreService, "Основной микросервис бизнес-логики", "Java, Spring")
Container(PaymentServiceDB, "База данных информации об оплате", "Postgres")
System_Ext(Bank, "ИС Банк", "Внешний банк для приема платежей")

Container(PaymentService,  "Сервис оплаты", "Java, Spring") {
  Component(PaymentServiceController, "Payment Service Controller", "API для обработки платежей и информации об оплате")
  Component(PaymentServiceLayer, "Service Layer", "Бизнес логика по обработке платежей и информации об оплате")
  Component(PaymentServiceRepositoryLayer, "Repository Layer", "Data access logic")
}

Rel(ApiGateway, PaymentServiceController, "Использует", "HTTP / REST")
Rel(CoreService, PaymentServiceController, "Использует", "HTTP / REST")
Rel(PaymentServiceController, PaymentServiceLayer, "Использует")
Rel(PaymentServiceLayer, PaymentServiceRepositoryLayer, "Использует")
Rel(PaymentServiceLayer, Bank, "Вызов API по оплате", "HTTP / REST")
Rel(PaymentServiceRepositoryLayer, PaymentServiceDB, "Чтение / Запись", "SQL")

@enduml