@startuml
title ИС Умный Дом - Core Service Component Diagram

top to bottom direction

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml
Container(ApiGateway, "API Gateway", "Java, Spring")
Container(UserService, "Сервис управления пользователями", "Java, Spring")
Container(MarketService, "Сервис продажи модулей и устройств ИС Умный Дом", "Java, Spring")
Container(PaymentService, "Сервис оплаты", "Java, Spring")
Container(DeviceService, "Сервис управления устройствами", "Java, Spring")
Container(TelemetryService, "Сервис телеметрии", "Java, Spring")
Container(ScenarioService, "Сервис управления сценариями", "Java, Spring")
Container(CoreServiceDB, "База данных информации процессов, истории выполнения операций", "Postgres")

Container(CoreService, "Основной микросервис бизнес-логики", "Java, Spring") {
  Component(CoreServiceController, "Core Service Controller", "API для обработки бизнес процессов, бизнес - логики ИС Умный Дом(процессы, кросс запросы и т.д.)")
  Component(CoreServiceLayer, "Service Layer", "Бизнес логика по продажи модулей и устройств ИС Умный Дом")
  Component(BPMEngine, "BPM Engine", "BPM Engine для обработки запросов")
  Component(CoreServiceRepositoryLayer, "Repository Layer", "Data access logic")
}

Rel(ApiGateway, CoreServiceController, "Запросы от пользователя", "HTTP / REST")
Rel(CoreServiceController, CoreServiceLayer, "Использует")
Rel(CoreServiceLayer, BPMEngine, "Использует")
Rel(CoreServiceLayer, CoreServiceRepositoryLayer, "Использует")
Rel(CoreServiceRepositoryLayer, CoreServiceDB, "Чтение / Запись", "SQL")

Rel(CoreServiceLayer, UserService, "Использует", "HTTP / REST")
Rel(MarketService, CoreServiceController, "Использует", "HTTP / REST")
Rel(CoreServiceLayer, PaymentService, "Использует", "HTTP / REST")
Rel(CoreServiceLayer, DeviceService, "Использует", "HTTP / REST")
Rel(TelemetryService, CoreServiceController, "Использует", "HTTP / REST")
Rel(ScenarioService, CoreServiceController, "Использует", "HTTP / REST")


@enduml